#!/usr/bin/env bash
#
# @(#) : user common aliases
#
# @version  1.0.0
# @author   Furukawa, Atsushi <atsushifx@aglabo.com>
# @date     2023-04-10
# @license  MIT
#
# @desc<<
#
#<<

echo "Exec: aliases"

alias ocaml='rlwrap ocaml '

