#!/usr/bin/env bash
#
# @(#) : user common aliases
#
# @version  1.0.0
# @author   Furukawa, Atsushi <atsushifx@aglabo.com>
# @date     2023-04-10
# @license  MIT
#
# @desc<<
#
#<<

echo "Exec: aliases"

# setup alias

# applications
alias www-browser="/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe"

# languages
alias ocaml="rlwrap -f . ocaml "
alias sml="rlwrap -f . sml "

