"" vim settings
"" @(#) vim user specific settings[
""
"
" @versiion  1.0.0
" @author    Furukawa, Atsushi <atsushifx@aglabo.com>
" @date      2022-07-02
" @license   MIT
"

""
" viminfo
set viminfo="n$XDG_CACHE_HOME/vim/_viminfo"

"" load default.vim
source $VIMRUNTIME/defaults.vim


"" package
set packpath+="$XDG_CONFIG_HOME/vimfiles"








"" vim common settings
" shell
set shell=pwsh


" encoding : default display Japanese
set fenc=utf-8
set encoding=utf-8
set fileformats=unix

" disp line number
set number


set virtualedit=block


set backspace=indent,eol,start


