"" vim settings
"" @(#) vim user specific settings
""
"
" @versiion  1.0.1
" @author    Furukawa, Atsushi <atsushifx@aglabo.com>
" @date      2023-03-01
" @license   MIT
"
" @description
" vim user default settings.
" set default directoris move to .config for using git.
"
"

"
" viminfo
set viminfofile="${XDG_DATA_HOME}/vim/_viminfo"

"" default
source $VIMRUNTIME/defaults.vim


"" setup for plugins
set packpath+=~/.config/vim

"" plugins
packadd vim-jetpack
"
call jetpack#begin()
" default plguins
Jetpack 'tani/vim-jetpack', {'opt': 1} "bootstrap

" plugin with vim-plug
Jetpack 'lambdalisue/fern.vim'
Jetpack 'editorconfig/editorconfig-vim'
Jetpack 'wakatime/vim-wakatime'


"
call jetpack#end()

"" vim common settings


" encoding : default display Japanese
set fenc=utf-8
set encoding=utf-8
set fileformats=unix

" 行番号
set number

" move cursor virtusalize
set virtualedit=block

"
set backspace=indent,eol,start

