#!/usr/bin/env bash
##
# @(#) .config/ bashrc : user defined bashrc
#
# user defined bashrc
# 

echo "Exec .config/bash/bashrc"

peco-history () {
  local _cmd
  _cmd=$( history 20|tac|sed -e "s/^[0-9 ]*//g"|peco )
  if [[ -n ${_cmd} ]]; then
    echo -n "Exec ${_cmd}"
  #  READLINE_LINE="$_cmd"
  #  READLINE_POINT=${#_cmd}
  fi
}

#
# prompt : set prompt for bash
#
_set_prompt() {
  local _colorprompt

  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    _color_prompt=yes
  else
    _color_prompt=
  fi

  if [ "$_color_prompt" = yes ]; then
    PS1='[\[\033[01;32m\]\u@\h\[\033[34m\] \W\[\033[00m\]] \$ '
  else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
  fi
  export PS1
}
_set_prompt

## key config
#bind -x '"\C-r": peco-history'


## bash completion
_cmpl_d=/home/linuxbrew/.linuxbrew/etc/bash_completion.d
for f in ${_cmpl_d}/*; do
  . "${f}"
done

# volta
# volta completions bash | bash
