#!/usr/bin/env bash
##
# @(#) user specific bashrc
#
# @version  1.0.2
# @date     2024-04-10
# @author   Furukawa, Atsushi <atsushifx@aglabo.com>
# @license  MIT
#
# @desc <<
# user specific bashrc
# user defined bashrc
#<<

# local env settings 

BASHRC_DIR="${XDG_CONFIG_HOME}/bash"
SCRIPTS_DIR="${BASHRC_DIR}/scripts"

#
# prompt : set prompt for bash
#
_set_prompt() {
  local _colorprompt

  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    _color_prompt=yes
  else
    _color_prompt=
  fi

  if [ "$_color_prompt" = yes ]; then
    PS1='[\[\033[01;32m\]\u@\h\[\033[34m\] \W\[\033[00m\]] \$ '
  else
    PS1='[ ${debian_chroot:+($debian_chroot)}\u@\h \w] \$ '
  fi
  export PS1
}
_set_prompt

## alias
if [[ -f "${XDG_CONFIG_HOME}/aliases" ]]; then
  source "${XDG_CONFIG_HOME}/aliases"
fi

## key config


## bash completion
_cmpl_d="${BASHRC_DIR}/bash_completion.d"
if [[ -e "${_cmpl_d}" ]]; then
  for f in ${_cmpl_d}/*; do
    echo "Exec: $f"
    . "${f}"
  done
fi

_cmpl_d="${HOMEVREW_PREFIX}/etc/bash_completion.d"
if [[ -e "${_cmpl_d}" ]]; then
  for f in ${_cmpl_d}/*; do
    source "${f}"
  done
fi

## wakatime-count
source ${XDG_CONFIG_HOME}/bash/scripts/bash-wakatime.sh

